//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class image
    {
        public int imageId { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<bool> isShow { get; set; }
        public byte[] imagepath { get; set; }
    
        public virtual product product { get; set; }
    }
}
