//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public int memberId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string email { get; set; }
        public string passw { get; set; }
        public Nullable<bool> isAdmin { get; set; }
    }
}
