//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class properties
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public properties()
        {
            this.propertyValues = new HashSet<propertyValues>();
        }
    
        public int propertyId { get; set; }
        public Nullable<int> productId { get; set; }
        public string propertyName { get; set; }
        public string propertyType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<propertyValues> propertyValues { get; set; }
        public virtual product product { get; set; }
    }
}
