//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class propertyValues
    {
        public int ValueId { get; set; }
        public Nullable<int> propertyId { get; set; }
        public string ValueName { get; set; }
    
        public virtual properties properties { get; set; }
    }
}
